#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2010 OpenWrt.org
# Copyright (C) 2006 Carlos Sobrinho

START=60

PROG=/bin/spotInspection
NAME=spotInspection


start()
{
	if [ $(pgrep -f spotInspection |wc -l) = "1" ]
	then
		kill $(pidof spotInspection)
	fi
	/bin/spotInspection
}

stop()
{
	kill $(pidof spotInspection)
}

