#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2010 OpenWrt.org
# Copyright (C) 2006 Carlos Sobrinho

START=99

PROG=/bin/spotInspection
NAME=spotInspection


start()
{
        kill $(pidof spotInspection_init)
        /root/spotInspection_init.sh
}

stop()
{
        kill $(pidof spotInspection_init)
}